# Generated by Django 4.0.2 on 2022-02-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameparticipation',
            old_name='is_win',
            new_name='is_alive',
        ),
        migrations.AddField(
            model_name='gameparticipation',
            name='is_eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
