# Generated by Django 4.0.2 on 2022-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_uid_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='is_gamekeeper',
            field=models.BooleanField(default=False),
        ),
    ]
