# Generated by Django 4.0.2 on 2022-03-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_start_dt_alter_round_start_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_round_idx',
            field=models.IntegerField(default=0),
        ),
    ]
