# Generated by Django 4.0.2 on 2022-03-19 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_current_round_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='zone_fullness',
            field=models.CharField(default=[], max_length=200, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
