# Generated by Django 4.0.2 on 2022-03-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_round_zone_fullness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='zone_fullness',
            new_name='_zone_fullness',
        ),
    ]
